// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGW8UslEM1d5hK6XzVshCUcAONcpqS5_o',
    appId: '1:634967700697:web:682c447d4f49898dc07ac8',
    messagingSenderId: '634967700697',
    projectId: 'scrumbot-fa40e',
    authDomain: 'scrumbot-fa40e.firebaseapp.com',
    databaseURL: 'https://scrumbot-fa40e-default-rtdb.firebaseio.com',
    storageBucket: 'scrumbot-fa40e.firebasestorage.app',
    measurementId: 'G-NJGBVKGPZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Se85Tg_c-g0Us-wCKW2ZVHgajMRRYf4',
    appId: '1:634967700697:android:41c0f5488240c81ec07ac8',
    messagingSenderId: '634967700697',
    projectId: 'scrumbot-fa40e',
    databaseURL: 'https://scrumbot-fa40e-default-rtdb.firebaseio.com',
    storageBucket: 'scrumbot-fa40e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ula8b0rs3NyUcG_z0sNPGm7HlTSCu7g',
    appId: '1:634967700697:ios:46344bed76c3684dc07ac8',
    messagingSenderId: '634967700697',
    projectId: 'scrumbot-fa40e',
    databaseURL: 'https://scrumbot-fa40e-default-rtdb.firebaseio.com',
    storageBucket: 'scrumbot-fa40e.firebasestorage.app',
    iosBundleId: 'com.example.proyecto1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ula8b0rs3NyUcG_z0sNPGm7HlTSCu7g',
    appId: '1:634967700697:ios:46344bed76c3684dc07ac8',
    messagingSenderId: '634967700697',
    projectId: 'scrumbot-fa40e',
    databaseURL: 'https://scrumbot-fa40e-default-rtdb.firebaseio.com',
    storageBucket: 'scrumbot-fa40e.firebasestorage.app',
    iosBundleId: 'com.example.proyecto1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGW8UslEM1d5hK6XzVshCUcAONcpqS5_o',
    appId: '1:634967700697:web:8a1b349625211dbec07ac8',
    messagingSenderId: '634967700697',
    projectId: 'scrumbot-fa40e',
    authDomain: 'scrumbot-fa40e.firebaseapp.com',
    databaseURL: 'https://scrumbot-fa40e-default-rtdb.firebaseio.com',
    storageBucket: 'scrumbot-fa40e.firebasestorage.app',
    measurementId: 'G-VPP18QY6J5',
  );
}
